2021-01-27 23:18:37,788 - CasaBlanca - ERROR: Could not build url for endpoint '/home'. Did you mean 'home' instead?
Traceback (most recent call last):
  File "C:\Users\pcc\Desktop\Escritorio\CasaBlanca\app.py", line 64, in loginVerify
    return redirect(url_for('/home'))
  File "c:\Users\pcc\Desktop\Escritorio\CasaBlanca\env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\Users\pcc\Desktop\Escritorio\CasaBlanca\env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\Users\pcc\Desktop\Escritorio\CasaBlanca\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\pcc\Desktop\Escritorio\CasaBlanca\env\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\Users\pcc\Desktop\Escritorio\CasaBlanca\env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/home'. Did you mean 'home' instead?
2021-01-28 00:03:25,472 - CasaBlanca - ERROR: 'NoneType' object has no attribute 'redirect'
Traceback (most recent call last):
  File "C:\Users\pcc\Desktop\Escritorio\CasaBlanca\app.py", line 64, in loginVerify
    if (authenticateResponse.redirect):
AttributeError: 'NoneType' object has no attribute 'redirect'
